title: "Alan's Blog"
description: "Notes on security, cryptography and engineering"

remote_theme: mmistakes/minimal-mistakes@4.27.3

plugins:
  - jekyll-include-cache

markdown: kramdown

author:
  name: "Alan Luo"
